---

# task file for dgnest.monit

- name: Update package repositories
  sudo: yes
  apt:
    update_cache: True
  when: ansible_distribution == "Ubuntu"
  tags:
    - apt
    - update_cache

- name: Install monit package dependencies
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  register: install_monit_package_dependencies
  when: _monit_package_dependencies is defined
  with_items: _monit_package_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_monit_package_dependencies.stdout_lines

- name: Install monit dependencies
  sudo: yes
  apt:
    name: "{{ item.name }}"
    state: present
  register: install_monit_dependencies
  when: _monit_dependencies is defined
  with_items: _monit_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_monit_dependencies.stdout_lines
