---
# task for dgnest.monit

- include: install.d/CentOS.yaml
  when: ansible_distribution == "CentOS"
  tags:
    - monit

- include: install.d/Ubuntu.yaml
  when: ansible_distribution == "Ubuntu"
  tags:
    - monit
