---
# task for dgnest.monit

- name: Install packages via pip monit
  sudo: yes
  pip: name="{{ item.name }}" version="{{ item.version }}"
  when: monit_pip_dependencies is defined
  with_items: monit_pip_dependencies
