---

# task file for dgnest.monit

- name: Ensure apt cache is up to date
  apt:
    update_cache: yes


- name: Install monit dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items: _monit_packages
  tags:
    - monit
